name: cd

on:
  push:
    branches: [main]

jobs:

  test:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build Prod
        runs: ./scripts/buildprod.sh
